namespace:
  description: Metadata related to ViaQ log collection pipeline. Everything about log collector, normalizers, mappings goes here. Data in this subgroup is stored for troublehsooting purposes mostly.
  fields:
    - name: "@version"
      type: keyword
      example: TODO
      description: Version of “com.redhat.viaq” mapping the document is intended to adhere by the normalizer. It must be set by the normalizer. The value must correspond to the [_meta][version].
    - name: collector
      type: group
      description: The section contains metadata specific to the collector.
      fields:
        - name: hostname
          type: keyword
          description: FQDN of the collector. It might be different from the FQDN of the actual emitter of the logs.
        - name: name
          type: keyword
          description: Name of the collector.
        - name: version
          type: keyword
          description: Version of the collector
        - name: ipaddr4
          type: ip
          description: IP address v4 of the collector server, can be an array.
          fields:
            - name: raw
              ignore_above: 256
              type: keyword
        - name: ipaddr6
          type: ip
          description: IP address v6 of the collector server, can be an array.
        - name: inputname
          type: keyword
          description: how the log message was received on the collector whether it was TCP/UDP, or maybe imjournal/imfile.
        - name: received_at
          type: date
          format: yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ||yyyy-MM-dd'T'HH:mm:ssZ||dateOptionalTime
          description: Time when the message was received at the collector.
        - name: original_raw_message
          type: text
          index: true
          doc_values: false
          description: The original non-parsed log message, collected by collector or as close to the source as possible.
          fields:
            - name: raw
              type: keyword
              ignore_above: 256
    - name: normalizer
      type: group
      description: The section contains metadata specific to the normalizer.
      fields:
        - name: hostname
          type: keyword
          description: FQDN of the normalizer.
        - name: name
          type: keyword
          description: Name of the normalizer.
        - name: version
          type: keyword
          description: Version of the normalizer
        - name: ipaddr4
          type: ip
          description: IP address v4 of the normalizer server, can be an array.
          fields:
            - name: raw
              ignore_above: 256
              type: keyword
        - name: ipaddr6
          type: ip
          description: IP address v6 of the normalizer server, can be an array.
        - name: inputname
          type: keyword
          description: how the log message was received on the normalizer whether it was TCP/UDP.
        - name: received_at
          type: date
          format: yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ||yyyy-MM-dd'T'HH:mm:ssZ||dateOptionalTime
          description: Time when the message was received at the collector.
        - name: original_raw_message
          type: text
          index: true
          doc_values: false
          description: The original non-parsed log message as it is received at the normalizer.
          fields:
            - name: raw
              type: keyword
              ignore_above: 256
    - name: trace
      type: text
      doc_values: false
      index: true
      analyzer: whitespace
      example: rsyslog,8.16,2016.02.01 logstash,1.5,2016.03.03
      description: The field records the trace of the message. Each collector/normalizer appends information about itself and the date/time when the message was processed.
  name: pipeline
  private: true
  type: group
