
The namespace for Kubernetes-specific metadata



=== kubernetes.pod_name

The name of the pod

[horizontal]
Data type:: keyword





=== kubernetes.pod_id

The Kubernetes ID of the pod

[horizontal]
Data type:: keyword





=== kubernetes.namespace_name

The name of the namespace in Kubernetes

[horizontal]
Data type:: keyword





=== kubernetes.namespace_id

The ID of the namespace in Kubernetes

[horizontal]
Data type:: keyword





=== kubernetes.host

The Kubernetes node name

[horizontal]
Data type:: keyword








=== kubernetes.container_name

The name of the container in Kubernetes

[horizontal]
Data type:: keyword







=== kubernetes.annotations

Annotations associated with the Kubernetes object

[horizontal]
Data type:: group





=== kubernetes.labels

Labels attached to the Kubernetes object. Each label name is a subfield of labels field. Each label name is de-dotted: dots in the name are replaced with underscores.

[horizontal]
Data type:: group




==== kubernetes.labels.deployment

The deployment associated with this Kubernetes object

[horizontal]
Data type:: keyword

Example value:: `logging-kibana-3`




==== kubernetes.labels.deploymentconfig

The deployment configuration associated with this Kubernetes object

[horizontal]
Data type:: keyword

Example value:: `logging-kibana`






==== kubernetes.labels.component

The component associated with this Kubernetes object

[horizontal]
Data type:: keyword

Example value:: `kibana`




==== kubernetes.labels.provider

The provider associated with this Kubernetes object

[horizontal]
Data type:: keyword

Example value:: `openshift`





