= ViaQ project documentation

WARNING: Under Construction

The ViaQ project provides components for https://docs.openshift.com/container-platform/4.7/logging/cluster-logging.html[Openshift Logging], a central log collection system for OpenShift clusters.

This site documents the architecture and some of the internal details of Openshift Logging.

This content is intended for developers, doc writers, and contributors working on the project.
It may be of interest to those who want to learn more about the internal details.

TIP: To contribute to this site, see https://github.com/ViaQ/documentation

== Documentation

* link:architecture/index.html[Logging architecture overview]
* xref:data_model/public/data_model.adoc[Log record data model for users]

== Other Resources

The project spans several repositories:

* link:https://github.com/ViaQ[ViaQ] contains repositories for components.
* https://github.com/ViaQ/documentation[ViaQ/documentation] contains this site.
* link:https://github.com/openshift/cluster-logging-operator[Cluster Logging Operator] deploys log collection and forwarding in a cluster.

Other project resources:

* link:https://issues.redhat.com/projects/LOG/issues/LOG-96?filter=allopenissues[Planning and issue tracking]
