== ⚠pipeline


Metadata related to ViaQ log collection pipeline. Everything about log collector, normalizers, mappings goes here. Data in this subgroup is stored for troublehsooting purposes mostly.

=== pipeline.@version


Version of “com.redhat.viaq” mapping the document is intended to adhere by the normalizer. It must be set by the normalizer. The value must correspond to the [_meta][version]. 

[horizontal]
Data type:: keyword

Example value:: TODO



=== pipeline.collector


The section contains metadata specific to the collector. 

[horizontal]
Data type:: group


==== pipeline.collector.hostname


FQDN of the collector. It might be different from the FQDN of the actual emitter of the logs. 

[horizontal]
Data type:: keyword



==== pipeline.collector.name


Name of the collector. 

[horizontal]
Data type:: keyword



==== pipeline.collector.version


Version of the collector 

[horizontal]
Data type:: keyword



==== pipeline.collector.ipaddr4


IP address v4 of the collector server, can be an array. 

[horizontal]
Data type:: ip


===== pipeline.collector.ipaddr4.raw


⚠ No description. 

[horizontal]
Data type:: keyword




==== pipeline.collector.ipaddr6


IP address v6 of the collector server, can be an array. 

[horizontal]
Data type:: ip



==== pipeline.collector.inputname


how the log message was received on the collector whether it was TCP/UDP, or maybe imjournal/imfile. 

[horizontal]
Data type:: keyword



==== pipeline.collector.received_at


Time when the message was received at the collector. 

[horizontal]
Data type:: date



==== pipeline.collector.original_raw_message


The original non-parsed log message, collected by collector or as close to the source as possible. 

[horizontal]
Data type:: text


===== pipeline.collector.original_raw_message.raw


⚠ No description. 

[horizontal]
Data type:: keyword





=== pipeline.normalizer


The section contains metadata specific to the normalizer. 

[horizontal]
Data type:: group


==== pipeline.normalizer.hostname


FQDN of the normalizer. 

[horizontal]
Data type:: keyword



==== pipeline.normalizer.name


Name of the normalizer. 

[horizontal]
Data type:: keyword



==== pipeline.normalizer.version


Version of the normalizer 

[horizontal]
Data type:: keyword



==== pipeline.normalizer.ipaddr4


IP address v4 of the normalizer server, can be an array. 

[horizontal]
Data type:: ip


===== pipeline.normalizer.ipaddr4.raw


⚠ No description. 

[horizontal]
Data type:: keyword




==== pipeline.normalizer.ipaddr6


IP address v6 of the normalizer server, can be an array. 

[horizontal]
Data type:: ip



==== pipeline.normalizer.inputname


how the log message was received on the normalizer whether it was TCP/UDP. 

[horizontal]
Data type:: keyword



==== pipeline.normalizer.received_at


Time when the message was received at the collector. 

[horizontal]
Data type:: date



==== pipeline.normalizer.original_raw_message


The original non-parsed log message as it is received at the normalizer. 

[horizontal]
Data type:: text


===== pipeline.normalizer.original_raw_message.raw


⚠ No description. 

[horizontal]
Data type:: keyword





=== pipeline.trace


The field records the trace of the message. Each collector/normalizer appends information about itself and the date/time when the message was processed. 

[horizontal]
Data type:: text

Example value:: rsyslog,8.16,2016.02.01 logstash,1.5,2016.03.03



