name: Deploy to GH Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get install -qq asciidoctor graphviz
        asciidoctor --version
        mkdir bin
        curl -o $PWD/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64
        chmod 755 $PWD/bin/gomplate
        $PWD/bin/gomplate --version
        echo "$PWD/bin" >> $GITHUB_PATH
    - name: Build Documentation
      run: make doc
    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
