name: Deploy PR preview to GH Pages

on:
  pull_request_target:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get install -qq asciidoctor graphviz
        mkdir bin
        curl -o $PWD/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64
        chmod 755 $PWD/bin/gomplate
        echo "$PWD/bin" >> $GITHUB_PATH
    - name: Build Documentation
      run: make all
    - name: Deploy Documentation Preview
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        destination_dir: previews/pr/${{ github.event.number }}/
    - uses: chrnorm/deployment-action@releases/v1
      name: Create Deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/previews/pr/${{ github.event.number }}/
        environment: previews/pr/${{ github.event.number }}
        ref: ${{ github.head_ref }}
        initial_status: success